<div class="breadcrumbs" id="breadcrumbs">
	<script type="text/javascript">
		try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
	</script>

	<ul class="breadcrumb">
		<li>
			<i class="ace-icon fa fa-home home-icon"></i>
			<a href="/">Home</a>
		</li>
		<?php foreach($this -> pages as $page):
			if($page -> id == 'home')
				continue;
		?>
			<?php if($page -> isActive()):?>
			<li class="active"><?php echo $page -> getLabel();?></li>
			<?php else:?>
			<li>
				<a href="<?php echo $page -> getHref();?>"><?php echo $page -> getLabel();?></a>
			</li>
			<?php endif;?>
		<?php endforeach;?>

	</ul><!-- /.breadcrumb -->
	<?php /* CLOSED *?>
	<!-- #section:basics/content.searchbox -->
	<div class="nav-search" id="nav-search">
		<form class="form-search">
			<span class="input-icon">
				<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
				<i class="ace-icon fa fa-search nav-search-icon"></i>
			</span>
		</form>
	</div><!-- /.nav-search -->

	<!-- /section:basics/content.searchbox -->
	<?php /* CLOSED */?>
</div>
