<?php $this -> headTitle('Logo Shopping Admin', 'APPEND') -> setSeparator(' - ');?>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta charset="utf-8" />
<?php echo $this -> headTitle();?>
<meta name="description" content="" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
<!-- bootstrap & fontawesome -->
<link rel="stylesheet" href="/assets/admin/css/bootstrap.min.css" />
<link rel="stylesheet" href="/assets/admin/css/font-awesome.min.css" />
<!-- page specific plugin styles -->
<?php echo $this -> pluginStyle();?>

<!-- text fonts -->
<link rel="stylesheet" href="/assets/admin/css/ace-fonts.css" />

<!-- ace styles -->
<link rel="stylesheet" href="/assets/admin/css/ace.min.css" />

<!--[if lte IE 9]>
	<link rel="stylesheet" href="/assets/admin/css/ace-part2.min.css" />
<![endif]-->
<link rel="stylesheet" href="/assets/admin/css/ace-skins.min.css" />
<link rel="stylesheet" href="/assets/admin/css/ace-rtl.min.css" />

<!--[if lte IE 9]>
  <link rel="stylesheet" href="/assets/admin/css/ace-ie.min.css" />
<![endif]-->

<!-- inline styles related to this page -->
<?php
echo $this -> headLink();
echo $this -> headStyle();
?>
<!-- ace settings handler -->
<script src="/assets/admin/js/ace-extra.min.js"></script>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lte IE 8]>
<script src="/assets/admin/js/html5shiv.js"></script>
<script src="/assets/admin/js/respond.min.js"></script>
<![endif]-->
<?php echo $this -> headScript();?>