<?php
	if(!count($this -> pages))
		return;
?>
<?php
foreach($this -> pages as $page):
	if(!$page -> isVisible())
		continue;
	$hasChildPages = $page -> hasPages();
	$icon = !empty($page -> iconClass) ? $page -> iconClass : 'fa-caret-right';
?>
	<li class="<?php echo $page -> isActive(true) ? 'active' : '';?>">
		<a href="<?php echo $page -> getHref();?>" class="<?php echo $hasChildPages ? 'dropdown-toggle' : '';?>">
			<i class="menu-icon fa <?php echo $icon;?>"></i>
			<span class="menu-text"><?php echo $page -> getLabel();?></span>
			<?php if($hasChildPages):?>
			<b class="arrow fa fa-angle-down"></b>
			<?php endif;?>
		</a>
		<b class="arrow"></b>
		<?php if($hasChildPages):?>
		<ul class="submenu">
			<?php echo $this -> partial('admin/partial/sidebar-navigation-list-items', array('pages' => $page -> getPages()));?>
		</ul>
		<?php endif;?>
	</li>
<?php endforeach;?>