<?php
$this -> headTitle("Login", 'SET');
$form = $this -> form;
$form -> prepare();
$form -> setAttribute('action', $this -> url('admin/default', array('controller' => 'auth', 'action' => 'login-post')));
?>
<?php $this -> headstyle() -> captureStart()?>
.login-box .alert-danger {margin-left: 0px; list-style-type: none; padding-top: 5px; padding-bottom: 5px;}
<?php $this -> headstyle() -> captureEnd()?>
<div class="col-sm-10 col-sm-offset-1">
	<div class="login-container">
		<div class="center">
			<h1>
				<i class="ace-icon fa fa-picture-o green"></i>
				<span class="red">Logo Shopping</span>
				<span class="white" id="id-text2">Admin</span>
			</h1>
			<h4 class="light-blue" id="id-company-text">&copy; Your Company Name</h4>
		</div>

		<div class="space-6"></div>

		<div class="position-relative">
			<div id="login-box" class="login-box visible widget-box no-border">
				<div class="widget-body">
					<div class="widget-main">
						<h4 class="header blue lighter bigger">
							<i class="ace-icon fa fa-coffee green"></i>
							<?php echo $this -> translate('Please Enter Your Information')?>
						</h4>

						<div class="space-6"></div>

						<?php
						echo $this -> form() -> openTag($form);
						$username = $form -> get('username');
						$password = $form -> get('password');
						?>
							<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger'));?>
							<fieldset>
								<label class="block clearfix">
									<span class="block input-icon input-icon-right">
										<?php echo $this -> formInput($username);?>
										<i class="ace-icon fa fa-user"></i>
									</span>
								</label>

								<label class="block clearfix">
									<span class="block input-icon input-icon-right">
										<?php echo $this -> formPassword($password);?>
										<i class="ace-icon fa fa-lock"></i>
									</span>
								</label>

								<div class="space"></div>

								<div class="clearfix">
									<button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
										<i class="ace-icon fa fa-key"></i>
										<span class="bigger-110"><?php echo $this -> translate('Login');?></span>
									</button>
								</div>

								<div class="space-4"></div>
							</fieldset>
						<?php echo $this -> form() -> closeTag();?>
						<div class="space-6"></div>
					</div><!-- /.widget-main -->
				</div><!-- /.widget-body -->
			</div><!-- /.login-box -->
		</div><!-- /.position-relative -->
	</div>
</div><!-- /.col -->
