<?php
$this -> headTitle("Login", 'SET');
$form = $this -> form;
$form -> prepare();
$form -> setAttribute('action', $this -> url('admin/default', array('controller' => 'auth', 'action' => 'login-post')));
?>
<?php $this -> headstyle() -> captureStart()?>
.login-box .alert-danger {margin-left: 0px; list-style-type: none; padding-top: 5px; padding-bottom: 5px;}
<?php $this -> headstyle() -> captureEnd()?>

<?php
echo $this -> form() -> openTag($form);
$username = $form -> get('username');
$password = $form -> get('password');
?>
	<header>
		Sign In
	</header>
	<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger'));?>
	<fieldset>
		<section>
			<?php echo $this -> formlabel($username)?>
			<label class="input">
				<i class="icon-append fa fa-user"></i>
				<?php echo $this -> formInput($username);?>
				<b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Please enter your username</b>
			</label>
		</section>

		<section>
			<?php echo $this -> formLabel($password);?>
			<label class="input">
				<i class="icon-append fa fa-lock"></i>
				<?php echo $this -> formPassword($password);?>
				<b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Enter your password</b>
			</label>
			<div class="note">
				<a href="forgotpassword.html">Forgot password?</a>
			</div>
		</section>

		<section>
			<label class="checkbox">
				<input type="checkbox" name="remember" checked="">
				<i></i>Stay signed in</label>
		</section>
	</fieldset>
	<footer>
		<button type="submit" class="btn btn-primary">
			Sign in
		</button>
	</footer>
<?php echo $this -> form() -> closeTag();?>
