<!DOCTYPE html>
<html lang="en">
	<head>
		<?php echo $this -> render('admin/partial/head');?>
	</head>

	<body class="login-layout blur-login">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<?php echo $this -> layout() -> content;?>
				</div><!-- /.row -->
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->

		<?php echo $this -> render('admin/partial/js');?>
		<!-- inline scripts related to this page -->
	</body>
</html>
